### ISSUE TITLE
Pre-trained model cannot download

### ISSUE THREAD

**Issue by Ruby-He** [Jeffkang-94/pytorch-adversarial-attack#1]
I cannot use the command 'bash download.sh' to download the model, please help me to resolve it. Thank you!

**Comment by Jeffkang-94** [comment]
Hello, Ruby. 
This is an ongoing private work, so it might be some errors I guess.
I will organize the sources and redesign the all works from now on.
btw, If you got errors when running `bash download.sh` as below, you have to install `curl` in your own environment.

`download.sh: line 3: curl: command not found
awk: cannot open ./cookie (No such file or directory)
download.sh: line 4: curl: command not found
download.sh: line 3: curl: command not found
awk: cannot open ./cookie (No such file or directory)
download.sh: line 4: curl: command not found
download.sh: line 3: curl: command not found
awk: cannot open ./cookie (No such file or directory)
download.sh: line 4: curl: command not found
download.sh: line 3: curl: command not found
awk: cannot open ./cookie (No such file or directory)
download.sh: line 4: curl: command not found
mkdir: cannot create directory ‘checkpoint’: File exists
mkdir: cannot create directory ‘checkpoint/ResNet’: File exists
mkdir: cannot create directory ‘checkpoint/WideResNet’: File exists
mv: cannot stat '1zAiPdXLPYkikxVnjXR8zcgEGer8HR3Ca.pth': No such file or directory
mv: cannot stat '1iAwkv18spCYaVEOi7IGDDHpgY9EB.pth': No such file or directory
mv: cannot stat 'clean.pth': No such file or directory
mv: cannot stat 'adv.pth': No such file or directory
mv: cannot stat '1uEQdXDIK4XPnm7ZkzLFtTrXb0WfAgi54.pth': No such file or directory
mv: cannot stat '1xdocjfDQ88LzLjYfkIJVSL9ImzrzUXZB.pth': No such file or directory
mv: cannot stat 'clean.pth': No such file or directory
mv: cannot stat 'adv.pth': No such file or directory
rm: cannot remove 'cookie': No such file or directory`

Just following the below command.
> sudo apt-get install curl

Otherwise, could u let me know your errors exactly?

**Comment by Ruby-He** [comment]
ok，thank you！I have downloaded by the link.



发自我的&nbsp;iPad


------------------ Original ------------------
From: Mingu Kang ***@***.***&gt;
Date: Mon,Jul 5,2021 1:46 PM
To: Jeffkang-94/pytorch-adversarial-attack ***@***.***&gt;
Cc: Ruby-He ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Jeffkang-94/pytorch-adversarial-attack] Pre-trained model cannot download (#1)





 
Hello, Ruby.
 This is an ongoing private work, so it might be some errors I guess.
 I will organize the sources and redesign the all works from now on.
 btw, If you got errors when running bash download.sh as below, you have to install curl in your own environment.
 
download.sh: line 3: curl: command not found awk: cannot open ./cookie (No such file or directory) download.sh: line 4: curl: command not found download.sh: line 3: curl: command not found awk: cannot open ./cookie (No such file or directory) download.sh: line 4: curl: command not found download.sh: line 3: curl: command not found awk: cannot open ./cookie (No such file or directory) download.sh: line 4: curl: command not found download.sh: line 3: curl: command not found awk: cannot open ./cookie (No such file or directory) download.sh: line 4: curl: command not found mkdir: cannot create directory ‘checkpoint’: File exists mkdir: cannot create directory ‘checkpoint/ResNet’: File exists mkdir: cannot create directory ‘checkpoint/WideResNet’: File exists mv: cannot stat '1zAiPdXLPYkikxVnjXR8zcgEGer8HR3Ca.pth': No such file or directory mv: cannot stat '1iAwkv18spCYaVEOi7IGDDHpgY9EB.pth': No such file or directory mv: cannot stat 'clean.pth': No such file or directory mv: cannot stat 'adv.pth': No such file or directory mv: cannot stat '1uEQdXDIK4XPnm7ZkzLFtTrXb0WfAgi54.pth': No such file or directory mv: cannot stat '1xdocjfDQ88LzLjYfkIJVSL9ImzrzUXZB.pth': No such file or directory mv: cannot stat 'clean.pth': No such file or directory mv: cannot stat 'adv.pth': No such file or directory rm: cannot remove 'cookie': No such file or directory
 
Just following the below command.
  
sudo apt-get install curl
  
Otherwise, could u let me know your errors exactly?
